spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=product
    username: ecommerce
    password: secret
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

app:
  internal:
    api-key: internal-service-key-12345
